services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      APP_ENV: docker
      YOLO_MODEL_PATH: ${YOLO_MODEL_PATH:-models/roboflow_productos.pt}
      YOLO_DEVICE: ${YOLO_DEVICE:-cpu}
      YOLO_CONFIDENCE_THRESHOLD: ${YOLO_CONFIDENCE_THRESHOLD:-0.001}
      OCR_ENGINE: ${OCR_ENGINE:-paddle}
    volumes:
      - ./runtime:/app/runtime
      - ./models:/app/models

